#!/bin/bash
set -euo pipefail

# ---------------------------------------------------------------------------
# Mock agent harness for testing the orchestrator.
# Reads /task/meta.json, simulates agent work, writes /output/result.json.
#
# Supports develop and review roles.
# Supports failure and timeout modes via meta.json flags:
#   "mock_mode": "success" (default), "failure", "timeout"
# ---------------------------------------------------------------------------

META_FILE="/task/meta.json"
OUTPUT_DIR="/output"
RESULT_FILE="${OUTPUT_DIR}/result.json"
REVIEW_FILE="${OUTPUT_DIR}/review.json"

# Read meta.json
if [ ! -f "$META_FILE" ]; then
  echo "ERROR: meta.json not found at $META_FILE" >&2
  echo '{"status":"failure","error_message":"meta.json not found"}' > "$RESULT_FILE"
  exit 1
fi

ROLE=$(jq -r '.role // "develop"' "$META_FILE")
ISSUE_ID=$(jq -r '.issue_id // 0' "$META_FILE")
BRANCH_NAME=$(jq -r '.branch_name // "unknown"' "$META_FILE")
ATTEMPT=$(jq -r '.attempt // 1' "$META_FILE")
MOCK_MODE=$(jq -r '.mock_mode // "success"' "$META_FILE")
MOCK_VERDICT=$(jq -r '.mock_verdict // "approved"' "$META_FILE")

echo "Mock agent starting: role=$ROLE issue=$ISSUE_ID attempt=$ATTEMPT mode=$MOCK_MODE"

# Handle timeout mode
if [ "$MOCK_MODE" = "timeout" ]; then
  echo "Simulating timeout — sleeping indefinitely..."
  sleep 3600
  exit 1
fi

# Handle failure mode
if [ "$MOCK_MODE" = "failure" ]; then
  echo "Simulating failure..."
  cat > "$RESULT_FILE" << EOF
{
  "status": "failure",
  "exit_code": 1,
  "error_message": "Mock agent simulated failure"
}
EOF
  exit 1
fi

# Success mode
if [ "$ROLE" = "develop" ]; then
  echo "Mock develop agent: creating test file and committing..."

  # Configure git for commits
  git config user.email "agent@orchestrator.local"
  git config user.name "Mock Agent"

  # Create a test file with task-specific content
  cat > "mock-change-issue-${ISSUE_ID}.txt" << EOF
Mock implementation for issue #${ISSUE_ID}
Attempt: ${ATTEMPT}
Branch: ${BRANCH_NAME}
Generated by mock agent at $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

  # Stage, commit, and push
  git add -A
  git commit -m "feat: mock implementation for issue #${ISSUE_ID}

Automated implementation for issue #${ISSUE_ID}
Attempt: ${ATTEMPT}"

  git push origin "$BRANCH_NAME" 2>/dev/null || git push -f origin "$BRANCH_NAME" 2>/dev/null || echo "Push failed (no remote configured) — continuing"

  echo "Mock develop agent: push complete."

  # Write result.json
  cat > "$RESULT_FILE" << EOF
{
  "status": "success",
  "exit_code": 0
}
EOF

elif [ "$ROLE" = "review" ]; then
  echo "Mock review agent: reviewing changes..."

  # Write review.json with configured verdict
  if [ "$MOCK_VERDICT" = "approved" ]; then
    cat > "$REVIEW_FILE" << EOF
{
  "verdict": "approved",
  "feedback": "All changes look good. Mock review approved."
}
EOF
  elif [ "$MOCK_VERDICT" = "changes_needed" ]; then
    cat > "$REVIEW_FILE" << EOF
{
  "verdict": "changes_needed",
  "feedback": "Mock review found issues. Please add error handling."
}
EOF
  elif [ "$MOCK_VERDICT" = "unclear" ]; then
    cat > "$REVIEW_FILE" << EOF
{
  "verdict": "unclear",
  "feedback": "Mock review could not determine quality. Human review needed."
}
EOF
  fi

  echo "Mock review agent: verdict=$MOCK_VERDICT"

  # Write result.json
  cat > "$RESULT_FILE" << EOF
{
  "status": "success",
  "exit_code": 0
}
EOF
fi

echo "Mock agent completed successfully."
exit 0
